README.adoc

Use `assert_nil` if expecting `nil`.
```ruby
assert_equal(nil, actual)
assert_nil(actual)
```
This rule prevents the following MT6's deprecated warning:
```ruby
class ExampleTest < Minitest::Test
def test_expecting_nil
foo = nil
assert_equal(nil, foo)
end
end
```
```console
% bundle exec rake test
Run options: --seed 16727
DEPRECATED: Use assert_nil if expecting nil from
/Users/koic/src/github.com/rubocop-hq/rubocop-minitest/test/rubocop/minitest_test.rb:13. This
will fail in Minitest 6.
```
https://github.com/seattlerb/minitest/blob/ab39d35fb4e84eb866ed9c4ecb707cbf3889de42/lib/minitest/assertions.rb#L203

Add "Assert Nil" rule

---

README.adoc

Many times we add wrong argument order for `assert_equal`. `assert_equal` should always have the first argument as `expected` value.

Added style guide for assert equal argument order

---

README.adoc

Sometimes I have seen developers making the mistake of using `assert_equal` to assert the boolean values. Adding cop to warn or correct this scenario would be nice.

Added style guide for assert true values

---

README.adoc

I saw it in one of the Rails PR. Test case for includes was added like `assert(collection.includes?(actual))` I am not able to find that PR but I think it is worth to add a cop to correct this scenario.

Add style guide for assert includes

---

README.adoc

`assert-includes` -> `assert_includes`

Fixed typo assert-includes -> assert_includes

---

README.adoc

I wanted to open this for discussion since Rails adds alias for all the `refute_` test case helper methods. Here is Rails code which adds alias to all the refute method https://github.com/rails/rails/blob/master/activesupport/lib/active_support/test_case.rb#L146-L159

Added style guide for refute_nil values

---

README.adoc

The documentation suggests using `assert_in_delta` when expecting float values -> https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L188
I have never used but I thought let's open a PR for discussion atleast. This stackover links explains nicely -> https://stackoverflow.com/questions/39743448/what-is-the-difference-between-minitests-assert-in-delta-and-assert-in-epsilon

Added style for assert float values

---

README.adoc

Fixes comment https://github.com/rubocop-hq/minitest-style-guide/pull/9/files#r315066207

Fixed the refute_nil bad example case

---

README.adoc

Style guide for `refute_includes` to check collection doesn't have the actual value.

Added style guide for refute_includes

---

README.adoc

This PR fixes a typo for assert includes an refute includes rules.
`assert_includes` and `refute_includes` methods assert using `include` instead of `includes`.
- https://github.com/seattlerb/minitest/blob/930ec0ba2e3ca010cca388a0429b33fd63c7d0bd/lib/minitest/assertions.rb#L239-L248
- https://github.com/seattlerb/minitest/blob/930ec0ba2e3ca010cca388a0429b33fd63c7d0bd/lib/minitest/assertions.rb#L615-L624

Fix a typo for assert includes and refute includes rules

---

README.adoc

Adds style guide for assert/refute_operator
Example: 
```
assert(5 > 3)
refute(3 > 5)
assert_operator(5, :>, 3)
refute_operator(3, :>, 5)
```

Adds style guide for assert/refute_operator

---

README.adoc

Adds style guide for `assert/refute_match`
```
assert(/rubocop/.match?(actual))
assert_match /rubocop/, actual
```

Adds style guide for assert/refute_match

---

README.adoc

`refute_equal` method uses `==` method, not `eql?` method.
https://github.com/seattlerb/minitest/blob/15ed8e4/lib/minitest/assertions.rb#L587-L592
`==` method and `eql?` method behave differently.
This PR will remove `eql?` method to maintain compatibility for bad case and good case behavior.

Use `==` method instead of `eql?` method for "Refute Equal" rule

---

README.adoc

Adds style guide for assert/refute_match
```
assert(object.respond_to?(some_method))
assert_respond_to(object, some_method)
```

Adds style guide for assert/refute_respond_to

---

README.adoc

Use `assert_instance_of` or `refute_instance_of` to check if a class is
or is not an instance of some class.
assert:
```ruby
assert_instance_of(String, 'rubocop-minitest')
```
refute:
```ruby
refute_instance_of(String, 'rubocop-minitest')
```

Add Rule to assert/refute Include Of

---

README.adoc

Fixes #25.
This PR adds global expectations rule.
It separates the problems solved by The Style Guide and RuboCop Minitest respectively.
This will be already solved by https://github.com/rubocop-hq/rubocop-minitest/pull/63.
```ruby
(1+1).must_equal 2
_(1 + 1).must_equal 2
value(1 + 1).must_equal 2
expect(1 + 1).must_equal 2
```
This will be implemented as a different Minitest cop than https://github.com/rubocop-hq/rubocop-minitest/pull/63.
```ruby
_(1 + 1).must_equal 2      # good
value(1 + 1).must_equal 2  # bad
expect(1 + 1).must_equal 2 # bad
_(1 + 1).must_equal 2      # bad
value(1 + 1).must_equal 2  # good
expect(1 + 1).must_equal 2 # bad
_(1 + 1).must_equal 2      # bad
value(1 + 1).must_equal 2  # bad
expect(1 + 1).must_equal 2 # good
```
This PR focuses on the issues that The …

[Fix #25] Add global expectations rule

---

README.adoc

This PR adds the style guides for assert/refute_predicate matcher. These matcher provide benefit in terms of readability of the code and user-friendly error message.

Added style guides for assert/refute_predicate

---

README.adoc

As suggested by @koic in https://github.com/rubocop-hq/rubocop-minitest/issues/111

Add `super` advice for hooks

---

README.adoc

I've noticed that it's common to get this backwards if you're used to RSpec.

Add RSpec comparison for expected/actual ordering

---

README.adoc

Minitest uses Ruby classes, if a Minitest class inherits from another class, it will also inherit its methods causing Minitest to run the parent's tests twice. In some cases, we want them to run them twice, but most of the time, we don't.
This warning is based on a [Rubocop rule](https://github.com/rubocop/rubocop-minitest/pull/164) for duplicated tests. [This blog](https://ignaciochiazzo.medium.com/dont-run-your-ruby-minitest-classes-twice-988645662cdb) post and [this library](https://github.com/ignacio-chiazzo/ruby-minitest-analyzer) contain more information.
Fixes https://github.com/rubocop/minitest-style-guide/issues/45

Added duplicated tests run hint.

---

README.adoc

As per https://github.com/rubygems/rubygems/blob/bd8d0835727e3eb2868675419bfeac2ecac40a0f/bundler/lib/bundler/templates/newgem/Rakefile.tt

Use `test_` prefix convention for gems

---

README.adoc

Follow up https://github.com/rubocop/rubocop-minitest/issues/256.
This PR removes an incorrect example from `Refute Equal` rule.
`assert(!"rubocop-minitest" == (actual))` is not compatible with good case.

Remove an incorrect example from `Refute Equal` rule
